all:
	arm-hisiv100-linux-uclibcgnueabi-gcc com.c -o com
	arm-hisiv100-linux-uclibcgnueabi-gcc crc.c -o crc
	arm-hisiv100-linux-uclibcgnueabi-gcc lck.c -o lck
	arm-hisiv100-linux-uclibcgnueabi-gcc msg.c -o msg
	arm-hisiv100-linux-uclibcgnueabi-gcc shm.c -o shm
	arm-hisiv100-linux-uclibcgnueabi-gcc tcpsrv.c -o tcpsrv
	arm-hisiv100-linux-uclibcgnueabi-gcc tcpcli.c -o tcpcli
	arm-hisiv100-linux-uclibcgnueabi-gcc sig.c -o sig -lrt
	arm-hisiv100-linux-uclibcgnueabi-gcc clk.c -o clk -lrt
	arm-hisiv100-linux-uclibcgnueabi-gcc fifosrv.c -o fifosrv
	arm-hisiv100-linux-uclibcgnueabi-gcc fifocli.c -o fifocli
	arm-hisiv100-linux-uclibcgnueabi-gcc err.c -o err
	arm-hisiv100-linux-uclibcgnueabi-gcc time.c -o time
