#! /bin/sh

/bin/mount -a

for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done
ifconfig lo up
ifconfig eth0 192.168.11.101

telnetd&

cd /ko
./load3520D

# spi                                     
#himm 0x200f0030 0x1
#himm 0x200f0034 0x1
#himm 0x200f0038 0x1
#himm 0x200f003c 0x1
#himm 0x200f0040 0x1

# i2c                                    
#himm 0x200f0044 0x0
#himm 0x200f0048 0x0

# uart1 - uart3
himm 0x200f0050 0x1
himm 0x200f0058 0x1
himm 0x200f005c 0x1
himm 0x200f0060 0x1
himm 0x200f00b8 0x1
himm 0x200f00bc 0x1

hwclock -s

#for exhibition0728 only
cd /root
insmod led_asc_mainbrd.ko
chmod +x led_fake.sh
./led_fake.sh &
#for exhibition0728 only

#mount -o nolock 192.168.11.180:/home/unionscience/asc /root/asc
. /root/.profile
asc --boot
